name: qa_logger
description: qa_logs is a Dart package designed to assist with monitoring and logging network calls within your application
version: 0.2.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  shelf_web_socket: ^1.0.4
  shelf: ^1.4.1
  flutter_express: ^0.7.2
  dio: ^5.4.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
