name: qa_logger
description: qa_logger is a Dart package that provides a simple and efficient way to monitor network calls and logs in your application. It's a good tool for QA and backend developers.
version: 0.4.3
repository: https://github.com/athulacaj/qa_logger

environment:
  sdk: ^3.4.0

# Add regular dependencies here.
dependencies:
  shelf_web_socket: ^3.0.0
  shelf: ^1.4.2
  dio: ^5.7.0
  flutter_express: ^0.8.4


dev_dependencies:
  lints: ^5.0.0
  test: ^1.21.0
